# Generated by Django 5.0.10 on 2024-12-19 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_products_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='products',
            table=None,
        ),
    ]
